name: Dependabot auto-approve
on: pull_request

permissions:
  # Mandatory for both the auto-merge enabling and approval steps
  pull-requests: write
  # Mandatory for the auto-merge enabling step
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-24.04
    steps:
      - name: Automatically merge Dependabot PRs
        uses: Scalingo/actions/dependabot-automerge@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
